setwd("C:/Users/Eric/Documents/R/exploraory_data_analysis")
cname <- names(read.table("household_power_consumption.txt", header= TRUE,sep = ";",stringsAsFactors = FALSE,nrows = 6))
data <- read.table("household_power_consumption.txt", header= TRUE,sep = ";",stringsAsFactors = FALSE,col.names = cname)
data1 <- subset(data,data$Date %in% c("1/2/2007","2/2/2007"))
data1[,3:9]<- lapply(data1[3:9],as.numeric)
data1$Date<-as.Date(data1$Date,format = "%d/%m/%Y")
data1$Time <-strptime(data1$Time,format = "%H:%M:%S")
png(filename = "plot1.png",width = 480,height = 480)
hist(data1$Global_active_power,main = "Global Active Power",col = "red",xlab = "Global Active Power(kilowatts)",ylab = "Frequency",breaks = 20)
dev.off()
