setwd("C:/Users/Eric/Documents/R/exploraory_data_analysis")
cname <- names(read.table("household_power_consumption.txt", header= TRUE,sep = ";",stringsAsFactors = FALSE,nrows = 6))
data <- read.table("household_power_consumption.txt", header= TRUE,sep = ";",stringsAsFactors = FALSE,col.names = cname)
data1 <- subset(data,data$Date %in% c("1/2/2007","2/2/2007"))
data1[,3:9]<- lapply(data1[3:9],as.numeric)
data1$wt<-with(data1,paste(Date,Time))
data1$wt<-strptime(data1$wt,format = "%d/%m/%Y %H:%M:%S")
png(filename = "plot3.png",width = 480,height = 480)
with(data1, plot(wt,Sub_metering_1,xlab = "",ylab = "Energy sub metering",type="l"))
with(data1,lines(wt,Sub_metering_2,type = "l",col="red"))
with(data1,lines(wt,Sub_metering_3,type = "l",col="blue"))
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"),lty = 1)
dev.off()
