setwd("C:/Users/Eric/Documents/R/exploraory_data_analysis")
cname <- names(read.table("household_power_consumption.txt", header= TRUE,sep = ";",stringsAsFactors = FALSE,nrows = 6))
data <- read.table("household_power_consumption.txt", header= TRUE,sep = ";",stringsAsFactors = FALSE,col.names = cname)
data1 <- subset(data,data$Date %in% c("1/2/2007","2/2/2007"))
data1[,3:9]<- lapply(data1[3:9],as.numeric)
data1$wt<-with(data1,paste(Date,Time))
data1$wt<-strptime(data1$wt,format = "%d/%m/%Y %H:%M:%S")
png(filename = "plot2.png",width = 480,height = 480)
with(data1, plot(wt,Global_active_power,xlab = "",ylab = "Global Active Power(kilowatts)",type="l"))
dev.off()
